stages:
    - build
    - push
    - staging
    - uat
    - release
    - production

cache:
  key:  ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository
    - target/

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true"

  # !todo: put vars in gitlab env var/file secrets, put here for ease of reproducibility
  PROJECT_IMAGE: petclinic_v2.2.0
  DOCKER_REGISTRY_ADDR: 192.168.33.9:5000
  DOCKER_USER: dev
  DOCKER_PASSWORD: devpassword
  DOCKER_IMAGE_TAGGED: $PROJECT_IMAGE:$CI_COMMIT_SHORT_SHA
  MAVEN_JAR_VERSION: "2.2.0.BUILD-SNAPSHOT"
  HTTPD_PORT: 8888
  HTTPD_DIRECTORY_NAME: $CI_PIPELINE_ID
  SELENIUM_UAT_TESTS_REPO: 'https://gist.githubusercontent.com/Sebastienn/fc883ea0389ca85c1df358b0690d8a46/raw'
  STAGING_EXPOSED_PORT: 8080
  PRODUCTION_EXPOSED_PORT: 8080
  STAGING_IP: http://192.168.33.7
  STAGING_ADDR: $STAGING_IP:$STAGING_EXPOSED_PORT
  PRODUCTION_PROPERTIES_FILE: |
                    # PRODUCTION PROPERTIES FILE
                    # Web
                    spring.thymeleaf.mode=HTML

                    # JPA
                    spring.jpa.hibernate.ddl-auto=none

                    # Internationalization
                    spring.messages.basename=messages/messages

                    # Actuator / Management
                    management.endpoints.web.base-path=/manage
                    management.endpoints.web.exposure.include=*

                    # Logging
                    logging.level.org.springframework=INFO
                    # logging.level.org.springframework.web=DEBUG
                    # logging.level.org.springframework.context.annotation=TRACE

                    # Maximum time static resources should be cached
                    spring.resources.cache.cachecontrol.max-age=12h


  STAGING_PROPERTIES_FILE: |
                    # STAGING PROPERTIES FILE
                    # Web
                    spring.thymeleaf.mode=HTML

                    # JPA
                    spring.jpa.hibernate.ddl-auto=none

                    # Internationalization
                    spring.messages.basename=messages/messages

                    # Actuator / Management
                    management.endpoints.web.base-path=/manage
                    management.endpoints.web.exposure.include=*

                    # Logging
                    logging.level.org.springframework=INFO
                    # logging.level.org.springframework.web=DEBUG
                    # logging.level.org.springframework.context.annotation=TRACE

                    # Maximum time static resources should be cached
                    spring.resources.cache.cachecontrol.max-age=12h


mvn_package:
    stage: build
    tags:
        - build
    artifacts:
      paths:
          - target/
          
    script:
        - mvn $MAVEN_CLI_OPTS package

docker_push:
    stage: push
    tags:
        - shell
    dependencies:
        - mvn_package
    script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY_ADDR
        - docker build -t $DOCKER_REGISTRY_ADDR/stage-$DOCKER_IMAGE_TAGGED --build-arg MAVEN_VERSION=$MAVEN_JAR_VERSION .
        - docker push $DOCKER_REGISTRY_ADDR/stage-$DOCKER_IMAGE_TAGGED
    only:
        - master
        

httpd_web_server:
    stage: push
    tags:
        - shell
    dependencies:
        - mvn_package
    script:
        - 'sed -i "s/<h1>/<h1> COMMIT SHA: #$CI_COMMIT_SHORT_SHA       PIPELINE ID: $CI_PIPELINE_ID        /" target/site/jacoco/index.html'
        - docker start web_server || (docker run -d --name web_server -p $HTTPD_PORT:80 httpd && docker exec web_server rm -f /usr/local/apache2/htdocs/index.html)
        - mkdir -p $(pwd)/$HTTPD_DIRECTORY_NAME/code_coverage/ && cp -r $(pwd)/target/site/jacoco/ $(pwd)/$HTTPD_DIRECTORY_NAME/code_coverage/
        - docker cp $(pwd)/$HTTPD_DIRECTORY_NAME web_server:/usr/local/apache2/htdocs/
    only:
        - master
        
       
deploy_staging:
    image: docker:latest
    stage: staging
    tags:
        - staging
    script:
        - docker stop petclinic_stage_container || true # used to always get a successful exit code in case the docker container is not yet deployed 
        - docker rm petclinic_stage_container || true
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY_ADDR
        - docker pull $DOCKER_REGISTRY_ADDR/stage-$DOCKER_IMAGE_TAGGED
        - touch application.properties && chmod 666 application.properties && echo "$STAGING_PROPERTIES_FILE" > application.properties
        - docker create --rm=true -p $STAGING_EXPOSED_PORT:8080 --name petclinic_stage_container $DOCKER_REGISTRY_ADDR/stage-$DOCKER_IMAGE_TAGGED
        - docker cp $(pwd)/application.properties petclinic_stage_container:/
        - rm -f application.properties
        - docker start petclinic_stage_container
    allow_failure: false
    environment:
        name: staging
        url: http://192.168.33.7
    only:
        - master
        
performance_test:
    stage: uat
    tags:
        - shell
    script:
        - artillery quick --count 20 -n 40 $STAGING_ADDR -o artillery_result -q
        - mkdir -p $(pwd)/$HTTPD_DIRECTORY_NAME/performance_report/ && cp -r $(pwd)/artillery_result $(pwd)/$HTTPD_DIRECTORY_NAME/performance_report/
        - docker cp $(pwd)/$HTTPD_DIRECTORY_NAME/performance_report/ web_server:/usr/local/apache2/htdocs/$HTTPD_DIRECTORY_NAME
    artifacts:
      paths:
          - ./artillery_result
    only:
        - master
        
selenium_uat:
    stage: uat
    tags:
        - shell
    script:
        - wget $SELENIUM_UAT_TESTS_REPO -O uat-selenium.py
        - chmod +x uat-selenium.py
        - python uat-selenium.py $STAGING_ADDR selenium_test_result.txt
        - mkdir -p $(pwd)/$HTTPD_DIRECTORY_NAME/uat_test_report/ && cp -r $(pwd)/selenium_test_result.txt $(pwd)/$HTTPD_DIRECTORY_NAME/uat_test_report/
        - docker cp $(pwd)/$HTTPD_DIRECTORY_NAME/uat_test_report/ web_server:/usr/local/apache2/htdocs/$HTTPD_DIRECTORY_NAME
        - rm -f uat-selenium.py
    allow_failure: false
    artifacts:
      paths:
          - ./selenium_test_result.txt
    only:
        - master

promote_image:
    image: docker:latest
    stage: release
    tags:
        - shell
    script:
        - docker tag $DOCKER_REGISTRY_ADDR/stage-$DOCKER_IMAGE_TAGGED $DOCKER_REGISTRY_ADDR/prod-$DOCKER_IMAGE_TAGGED
        - docker push $DOCKER_REGISTRY_ADDR/prod-$DOCKER_IMAGE_TAGGED
    when: manual
    allow_failure: false
    only:
        - master
        
deploy_production:
    image: docker:latest
    stage: production
    tags:
        - production
    script:
        - docker stop petclinic_prod_container || true
        - docker rm petclinic_prod_container || true
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY_ADDR
        - docker pull $DOCKER_REGISTRY_ADDR/prod-$DOCKER_IMAGE_TAGGED
        - touch application.properties && chmod 666 application.properties && echo "$PRODUCTION_PROPERTIES_FILE" > application.properties
        - docker create --rm=true -p $PRODUCTION_EXPOSED_PORT:8080 --name petclinic_prod_container $DOCKER_REGISTRY_ADDR/prod-$DOCKER_IMAGE_TAGGED
        - docker cp $(pwd)/application.properties petclinic_prod_container:/
        - rm -f application.properties
        - docker start petclinic_prod_container
    environment:
        name: production
        url: http://192.168.33.5
    when: manual
    allow_failure: false
    only:
        - master
