stages:
        # - build
        # - push
        - staging

before_script:
        - export CURRENT_DATETIME=`date +"%Y%m%d-%H%M%S"`
services:
  - name: docker:dind

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - target/

variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository

# build:
#         image: maven:3-jdk-8
#         stage: build
#         cache:
#                 key: "$CI_COMMIT_REF_NAME"
#                 policy: push
#                 paths:
#                         - target/
#                         - .m2/
#         cache:
#             key: "$CI_COMMIT_REF_NAME"
#             paths:
#                 - target/
#         artifacts:
#           paths:
#             - target/
#         script:
#                 - ./mvnw package

# docker_push:
#         image: docker:latest
#         stage: push
#         tags: [shell]
#         script:
#                 - echo "$CI_COMMIT_REF_NAME"
#                 - docker login -u "dev" -p "devpassword" http://192.168.33.9:5000
#                 - docker build --pull -t "$CURRENT_DATETIME" -t "staging" .
#                 - docker tag "$CURRENT_DATETIME" 192.168.33.9:5000/$CURRENT_DATETIME
#                 - docker tag "staging" 192.168.33.9:5000/staging
#                 - docker push 192.168.33.9:5000/$CURRENT_DATETIME
#                 - docker push 192.168.33.9:5000/staging
#         only:
#                 - master

deploy_staging:
    image: tmaier/docker-compose:latest
    stage: staging
    tags: [shell]
    script:
        # - docker login -u "dev" -p "devpassword" http://192.168.33.9:5000
        # - docker pull "192.168.33.9:5000/staging"
        # - docker-compose -f docker-compose.yml pull
        # - docker-compose -f docker-compose.yml up -d
        - touch /home/vagrant/test.txt
    environment:
        name: staging
        url: http://192.168.33.7
    only:
        - master
